/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f401xx.h>

void delay(){
	for(int i = 0; i < 1000000; i++);
}
int main(void)
{
		RCC->AHB1ENR |= (1<<0);

		GPIOA->MODER |= (1 << (2*2));

		GPIOA->ODR |= (1 << 2);

    /* Loop forever */
	while(1){
		GPIOA -> ODR &= (0 << 2);
		delay();
		GPIOA -> ODR |= (1 << 2);
		delay();
	}
}
